config/routes.rb
Rails.application.routes.draw do
  get "new", to: "games#new"
  post "score",to: "games#score"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/games_controller.rb
require 'json'
require 'open-uri'

class GamesController < ApplicationController
  def new
    @letters = (0...8).map { (65 + rand(26)).chr }.join
  end

  def score
    raise
    @letters = params[:letters].downcase.split('')
    @input = params[:word].split('')

    number_of_included_letters = @input.all? { |letter| @letters.include?(letter)}
    number_of_letters_in_word = @input.size
    letters_are_included = number_of_included_letters == number_of_letters_in_word
    if letters_are_included
      url = "https://wagon-dictionary.herokuapp.com/#{@input.join("")}"
      user_check = open(url).read
      answer = JSON.parse(user_check)
      word_exists = answer["found"]
      if word_exists
        @result = "congrats"
      else
        @result = "word doesn't exist"
      end
    else
        @result = "word doesn't use required letters"
    end

    #The word can’t be built out of the original grid
    #The word is valid according to the grid, but is not a valid English word
    #The word is valid according to the grid and is an English word
    #faire une requete get avec l'api

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/new.html.erb
<h1>New Game</h1>

<%= @letters %>

<p>What is the longest word you can find ?</p>
<form action=/score method="post">
<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
<%= hidden_field_tag :letters, @letters %>
  <input type="text" name="word">
  <input type="submit" value="Play">
</form>

app/views/games/score.html.erb
  <h2>Result</h2>


    <%= @input %>

  <%= link_to "Play Again", score_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>